// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZlY1NhW--kGGTY3zA62C4MSuPlJ_Pb8',
    appId: '1:1035295223541:web:57b8d2874ee0e76ff9dfbc',
    messagingSenderId: '1035295223541',
    projectId: 'beritabola-app',
    authDomain: 'beritabola-app.firebaseapp.com',
    storageBucket: 'beritabola-app.appspot.com',
    measurementId: 'G-SJ621VEQ25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjKupHia-uXAcFlTQb5Jf24Hi4uAIp8hE',
    appId: '1:1035295223541:android:9da71fb40f0e0361f9dfbc',
    messagingSenderId: '1035295223541',
    projectId: 'beritabola-app',
    storageBucket: 'beritabola-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnwK3qiWUbaeV3xaPFj-J6REk5wqoO73I',
    appId: '1:1035295223541:ios:02eae5fd4dca3247f9dfbc',
    messagingSenderId: '1035295223541',
    projectId: 'beritabola-app',
    storageBucket: 'beritabola-app.appspot.com',
    iosBundleId: 'com.example.beritabolaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnwK3qiWUbaeV3xaPFj-J6REk5wqoO73I',
    appId: '1:1035295223541:ios:c2350c441e57edaff9dfbc',
    messagingSenderId: '1035295223541',
    projectId: 'beritabola-app',
    storageBucket: 'beritabola-app.appspot.com',
    iosBundleId: 'com.example.beritabolaApp.RunnerTests',
  );
}
